id: IECF545CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T15:56:11+00:00'
last_modified: '2022-06-09T17:51:06.399931+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017144
  title: མཁས་གྲུབ་སྦྱིན་པ་དར་རྒྱས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    96CD:
      image_group_id: I00EGS1017146
      title: Volume 1 of
      total_pages: 246
      order: 1
      base_file: 96CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
